name: Deploy to shinyapps.io
on:
  push:
    branches:
      - cicd
jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: rstudio/r-base:4.3.0-focal
    steps:
      - name: Install SSL
        run: |
          sudo apt update
          sudo apt install libssl-dev

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Activate renv
        uses: r-lib/actions/setup-renv@v2

      - name: Run tests using testthat
        run: Rscript -e "source('control/testthat.R')"
