name: Deploy to shinyapps.io
on:
  push:
    branches:
      - cicd
jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: r-base:4.3.0
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install curl
        run: apt-get install curl

