name: Deploy to shinyapps.io
on:
  push:
    branches:
      - cicd
jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: rstudio/r-base:4.3.0-focal
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Activate renv
        run: Rscript -e "renv::activate()"
      - name: Load cached packages
        uses: actions/cache@v3
        with:
          path: /renv
          key: ${{ hashFiles('renv.lock') }}
