name: Deploy to shinyapps.io
on:
  push:
    branches:
      - cicd
jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: rstudio/r-base:4.3.0-focal
    steps:
      - name: Install SSL
        run: |
          sudo apt update
          sudo apt install libssl-dev

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Activate renv
        run: |
          Rscript -e "Sys.setenv(RENV_CONFIG_SANDBOX_ENABLED = FALSE)"
          Rscript -e "renv::activate()"

      - name: Load/Cache packages
        id: renv-cache
        uses: actions/cache@v3
        with:
          path: renv
          key: ${{ hashFiles('renv.lock') }}

      - name: Install packages
        if: steps.renv-cache.outputs.cache-hit != 'true'
        run: Rscript -e "renv::restore(prompt = F)"

      - name: Run testthat
        run: Rscript -e "source('control/testthat.R')"
