name: Deploy to shinyapps.io
on:
  push:
    branches:
      - cicd
jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: r-base:4.3.0
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Activate renv
        run: |
          Rscript -e "renv::activate()"
          Rscript -e "renv::restore(prompt = F)"
          Rscript -e "paste('Loaded renv:', packageVersion("renv"))"

      - name: Run testthat
        run: Rscript -e "source('control/testthat.R')"
