name: Deploy to shinyapps.io
on:
  push:
    branches:
      - cicd
jobs:
  # tests:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: rstudio/r-base:4.3.0-focal
  #   steps:
  #     - name: Install SSL
  #       run: |
  #         sudo apt update
  #         sudo apt install libssl-dev
  #
  #     - name: Checkout repo
  #       uses: actions/checkout@v3
  #
  #     - name: Activate renv
  #       uses: r-lib/actions/setup-renv@v2
  #
  #     - name: Run tests using testthat
  #       run: Rscript -e "source('control/testthat.R')"
    deploy:
        runs-on: ubuntu-latest
        env:
          # IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
          IMAGE_NAME: europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}/${{ secrets.GCP_APP_NAME }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          GCP_APP_NAME: ${{ secrets.GCP_APP_NAME }}
        steps:

        - name: Checkout repository
          uses: actions/checkout@v3

        - id: auth
          uses: google-github-actions/auth@v1
          with:
            credentials_json: ${{ env.GCP_CREDENTIALS }}

        - name: Set up Cloud SDK
          uses: google-github-actions/setup-gcloud@v1

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: ${{ env.IMAGE_NAME }}
            cache-from: type=gha
            cache-to: type=gha,mode=max

        - name: Deploy Docker image
          run: |
            gcloud run deploy ${{ env.GCP_APP_NAME }} \
            --image ${{ env.IMAGE_NAME }} \
            --region europe-west3 \
            --platform managed \
            --port=3838 \
            --allow-unauthenticated


