name: Deploy to shinyapps.io
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'

      - name: Install curl
        run: sudo apt-get install libcurl4-openssl-dev

      - name: Activate renv
        uses: r-lib/actions/setup-renv@v2

      - name: Run testthat
        run: Rscript -e "source('control/testthat.R')"

  deploy:
    needs: tests
    runs-on: ubuntu-latest
    env:
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'

      - name: Install curl
        run: sudo apt-get install libcurl4-openssl-dev

      - name: Activate renv
        uses: r-lib/actions/setup-renv@v2

      - name: Deploy
        run: Rscript -e "source('control/deploy.R')"
